services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ecommerce-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  ecommerce-data:
